### ISSUE TITLE
Timestamps are wrong when uploading gpx files to smashrun/rk

### ISSUE THREAD

**Issue by cwayne18** [cwayne18/ActivityTracker#1]

**Comment by sergiqp** [comment]
I haven't found any option to upload gpx files from the app. I have upload them manually navigating to ~/.local/share/activitytracker.cwayne18.

**Comment by cwayne18** [comment]
@sergiqp Work for uploading from the app is ongoing, I've just been pulling them manually as well.  Out of curiosity, which services are you uploading them to?

**Comment by sergiqp** [comment]
I want to uploading them to Dropbox. That way I can use it for many desktop applications and in other devices.

I'll wait for this to be a feature in the future. Thanks.
