### ISSUE TITLE
Where is the .gpx file?

### ISSUE THREAD

**Issue by gtriderxc** [cwayne18/ActivityTracker#10]
"Creates a .gpx file that can then be uploaded to Fitbit/Runkeeper/Smashrun/Strava/whatever". And how should we upload the file if we do not see it? Where can we find it and why not in a public folder that can be read from my pc? :-)

**Comment by zacardec** [comment]
Hello,

You can find it in this folder: home/phablet/.cache/share/activitytracker.cwayne18
You can read it with your pc with terminal.
You can copy it in a public folder with cp command .
:)
But i'm agree with you, it will be a good idea to have an "sync button" in the app to copy *.gpx on a pc folder.
:)

**Comment by gtriderxc** [comment]
We dont need a sync button i think. All we need is the file saved in a more accesible localization. I have no "share" in my cache :-( still can't find it.

  Am Do., 24. Dez. 2015 um 8:51 hat zacardecnotifications@github.com Folgendes geschrieben:  
Hello,

You can find it in this folder: home/phablet/.cache/share/activitytracker.cwayne18
You can read it with your pc with terminal.
You can copy it in a public folder with cp command .
:)
But i'm agree with you, it will be a good idea to have an "sync button" in the app to copy *.gpx on a pc folder.
:)

**Comment by cwayne18** [comment]
Sorry for the late response, it's actually in /home/phablet/.local/share/activitytracker.cwayne18

I can look into maybe storing it in somewhere like ~/Documents instead, but I'm not sure how feasible that is.  In the mean time, I am working on syncing from the app :)

**Comment by gtriderxc** [comment]
Nope, I still can't find the file ;-)There are only nokia_xxxx.png, nokia_version and "queue1",...2,...3 and ...4 files but no gpx.

Cheers 

```
  From: Chris Wayne <notifications@github.com>
```

 To: cwayne18/ActivityTracker ActivityTracker@noreply.github.com 
Cc: gtriderxc gtriderxc@yahoo.com
 Sent: Tuesday, December 29, 2015 7:04 PM
 Subject: Re: [ActivityTracker] Where is the .gpx file? (#10)

Sorry for the late response, it's actually in /home/phablet/.local/share/activitytracker.cwayne18I can look into maybe storing it in somewhere like ~/Documents instead, but I'm not sure how feasible that is. In the mean time, I am working on syncing from the app :)—

**Comment by cwayne18** [comment]
Are you sure you're looking in /home/phablet/.local/share/activitytracker.cwayne18/ ?

None of those files that you listed would make sense being in that directory..

**Comment by gtriderxc** [comment]
I found them! Sorry and many thanks!I love this app :-)

```
  From: Chris Wayne <notifications@github.com>
```

 To: cwayne18/ActivityTracker ActivityTracker@noreply.github.com 
Cc: gtriderxc gtriderxc@yahoo.com
 Sent: Saturday, January 2, 2016 6:06 PM
 Subject: Re: [ActivityTracker] Where is the .gpx file? (#10)

Are you sure you're looking in /home/phablet/.local/share/activitytracker.cwayne18/ ?None of those files that you listed would make sense being in that directory..—

**Comment by cwayne18** [comment]
Hey thanks, glad to hear it :)
