### ISSUE TITLE
No tracking with screen lock activated

### ISSUE THREAD

**Issue by corvusd** [cwayne18/ActivityTracker#13]
First of all, THANK YOU! It is a fantastic and essential application for Ubuntu Phone system.

This problem,I think, is the most important, as the most natural way to use your application is doing an activity to conserve battery power and the screen turn off.

Is it possible, as I have left written in the comments of the ubuntu store, the developer UNAV and join me and you share your technical knowledge to improve your application or both?

Thank you very much my system is Ubuntu Edition 4.5 bq Aquaris with the latest OTA-8.5

Cheers,

David Gámiz Jiménez

**Comment by cwayne18** [comment]
Hiya, 

Thanks for the comments!  Unfortunately, it is by Ubuntu's design that we _can't_ do anything when the screen is off.  This is very clear and explicit in the app's lifecycle system.  So nothing I can do (nor can the dev behind uNav).  Sorry!  I'd fix this issue if I could :)

**Comment by corvusd** [comment]
Right now the Ubuntu design team have open this issue and planned to resolve in next OTA? If not, it possible open bug for you?

**Comment by cwayne18** [comment]
It's not scheduled to be fixed anytime soon as far as I know :/

**Comment by corvusd** [comment]
OK. I see, I try find open the bug in the main project... Maybe talk with Marcos Costales on someplace of social net... like google+... thanks! Great job! :D
